name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [linux-386, linux-amd64, darwin-amd64, darwin-arm64, windows-386, windows-amd64]
        include:
          - arch: linux-386
            goos: linux
            goarch: 386
          - arch: linux-amd64
            goos: linux
            goarch: amd64
          - arch: darwin-amd64
            goos: darwin
            goarch: amd64
          - arch: darwin-arm64
            goos: darwin
            goarch: arm64
          - arch: windows-386
            goos: windows
            goarch: 386
          - arch: windows-amd64
            goos: windows
            goarch: amd64
        
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: mkdir -p bin/${{ matrix.goos }}/${{ matrix.goarch }}
    - name: Build
      run: go build -o bin/${{ matrix.goos }}/${{ matrix.goarch }}/Kotone-DiVE
      env:
        GOARCH: ${{ matrix.goarch }}
        GOOS: ${{ matrix.goos }}
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/tpc3/kotone-dive:latest

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
      # Artifact name
        path: bin
